modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Discusser/TNTArrows/issues"
license = "MIT"

[[mods]]
modId = "tntarrows"
version = "${version}"
displayName = "TNT Arrows"
authors = "Discusser"
description = '''
Adds arrows that can be mixed with TNTs for explosive effects!
'''
logoFile = "assets/tntarrows/icon.png"

[[dependencies.tntarrows]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tntarrows]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tntarrows]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"