modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tntarrows"
version = "${version}"
displayName = "TNT Arrows"
authors = "Discusser"
description = '''
Adds arrows that can be mixed with TNTs for explosive effects!
'''
logoFile = "assets/tntarrows/icon.png"

[[dependencies.tntarrows]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tntarrows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tntarrows]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"